# -*- coding: utf-8 -*-
"""Pythonlab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUqBzmbdHwTJtZRHer8KDWw9GQHPMmL0
"""

print("HELLO WORLD");

print("kaushik Sharma");

print("Hello","How are you");

print("I am","kaushik","Sharma");

print("Hello","how are you",sep="---")

print("I","AM","Kaushik",sep="---")

print("hi",end=" ")
print("hi")
print("!")

print('Hello,world!');
print("Hello,World!");
#print("" Hello,World"");
print("""Hello,World!""");

print("""""Kaushik""""")

print("Hello! "*3)

print("hello,%s"%"Guys")

print("Hello ","world",2025)

import sys
sys.stdout.write("IIST")

print("Hello,\"python is Fun!\"")

print(f"{'Python':<10} is awesome")

print(f"{'Python':>10} is Awesome")

print(f"{'python':^10}")

print("Kaushik")
print(20)
print("Indore")

print("Loading...")

print("Hi!,\"Kaushik is having fun with python!\"")

print("Hobbies:","Photography")

print("Python Rocks! "*5)

print("Red","Green","Blue",sep='-')

print(f"{'Name':^10 },Age")
print(f"{'Alice':^10 }",20)
print(f"{'Bob':^10 }",25)